environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk

install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-24
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tool
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-24.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools,tools,extra-android-m2repository, extra-android-support

test_script:
  - gradlew.bat build

build: off